### PR TITLE
Add neuralbeagle as a new llm model

### PR DESCRIPTION
**Pull request by MB-Finski**
Adds support for the NeuralBeagle14 7B 8K context length model. 

- [x] Model download tested as working

### CODE REVIEW

**Comment by marcelklehr** [comment]
What's with the failing CI?

**Comment by MB-Finski** [comment]
> What's with the failing CI?

Hmm.. I *think* it might be related to this: https://github.com/ggerganov/llama.cpp/issues/3484

So we may need to update the falcon gguf model file.

**Comment by MB-Finski** [comment]
Yup.. We will have to update the falcon model with this: https://gpt4all.io/models/gguf/gpt4all-falcon-newbpe-q4_0.gguf

**Review by provokateurin — APPROVED** [review]

**Comment by provokateurin** [comment]
This will close https://github.com/nextcloud/llm/issues/29

**Review by marcelklehr — APPROVED** [review]

**Pull request merged**
